# Generated by Django 4.1.5 on 2023-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_images')),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Uploads',
                'verbose_name_plural': 'Uploadss',
            },
        ),
    ]
