# Generated by Django 4.1.5 on 2023-01-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
    ]
