# Generated by Django 4.1.5 on 2023-01-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_description_author_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='author',
            new_name='authors',
        ),
    ]
